### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by varunchandak** [triggerdotdev/jsonhero-web#135]
got Application Error when using https://ip-ranges.amazonaws.com/ip-ranges.json

<img width="779" alt="image" src="https://user-images.githubusercontent.com/18713091/204512810-acbdd3f7-31c9-41dd-a313-a1caaeb2e8e2.png">

**Comment by ericallam** [comment]
Thanks for the report @varunchandak, this happens whenever JSON Hero tries to render a large JSON file, and is a known issue (and something we definitely want to fix!).

**Comment by eden881** [comment]
Is there any progress on this? Or alternatively is there a way to configure a larger JSON size limit when running the app locally?
