### ISSUE TITLE
Feature request: collapse-all in tree view

### ISSUE THREAD

**Issue by cueman** [triggerdotdev/jsonhero-web#149]
If you're working with a non-trivial JSON file in a tree view, then it's sometimes useful to be able to collapse everything (aka fold all) and then open only the nodes you want to.

Without that, it can be difficult to see what's there.

**Comment by parthvnp** [comment]
Happy to provide a fix for this!

**Comment by roxanne-mackinnon** [comment]
Currently working on this. /attempt #149

**Comment by parthvnp** [comment]
Might give it a try as well. /attempt [#149](https://github.com/triggerdotdev/jsonhero-web/issues/149)

**Comment by parthvnp** [comment]
@ericallam I have finished most of the functionality for this. I am just wondering whether this feature should be exposed via a shortcut or a button on Tree View page or both?

**Comment by ericallam** [comment]
@parthvnp juat a keyboard shortcut for now:

A commonly used keyboard shortcut for collapsing all nodes in a tree view on both macOS and Windows is:

- macOS: Command + Option + Left Arrow
- Windows: Ctrl + Alt + Left Arrow

**Comment by SSHari** [comment]
I thought I might try my hand at this as well /attempt #149
