### ISSUE TITLE
Chore: upgrade to latest remix

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/jsonhero-web#15]

**Comment by moyzlevi** [comment]
I wanna take this one

**Comment by jemiluv8** [comment]
I'd like to work on this
/attempt #15

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this one?

**Comment by kunal00000** [comment]
Hello @ericallam, is this issue still available to solve?

**Comment by rishi-raj-jain** [comment]
@samejr Is this no longer needed then?

**Comment by rishi-raj-jain** [comment]
@samejr Is this no longer needed then?

**Comment by samejr** [comment]
This is still an available bounty issue 👍

**Comment by rishi-raj-jain** [comment]
@samejr Please assign this to me?

**Comment by rishi-raj-jain** [comment]
Oh I see https://github.com/triggerdotdev/jsonhero-web/pull/167 already there, in case that's not working, please defer to me!

**Comment by samejr** [comment]
No feel free to make an attempt, we'll choose the best PR to merge when we have chance to check them out. The full bounty is still available while the issue is still open, we'll always reward based on quality not speed.

**Comment by abebeos** [comment]
> when we have chance to check them out.

You're kidding? 3 months, and the PR is still unprocessed?

It's `bounties`, not `slave labor`.

**Comment by samejr** [comment]
Sorry @abebeos this one definitely slipped our attention for too long. Our bad.
