### ISSUE TITLE
"Go" button on homepage should indicate loading state after clicking

### ISSUE THREAD

**Issue by abhaykv04** [triggerdotdev/jsonhero-web#151]
The "Go" button doesn't show any sort of loading state when clicked. If the pasted JSON is big, it can take significant amount of time for it to get parsed. So, it becomes important to show user some sort of loading state.

https://user-images.githubusercontent.com/19573579/232228775-051421aa-515d-4708-8928-ab4d7f05ae74.mov

I would like to work on it, if accepted. Thanks.

**Comment by matt-aitken** [comment]
Fixed by #150

**Comment by matt-aitken** [comment]
This would be great to do. Remix's`useTransition` is built to do this: https://remix.run/docs/en/1.15.0/hooks/use-transition#usetransition

**Comment by abhaykv04** [comment]
@matt-aitken Yes, I had the same approach in mind. Thanks for the suggestion. Just one question: What should be the label of button while it's in loading state?
