### ISSUE TITLE
App crashes when you leave it open for a long time

### ISSUE THREAD

**Issue by bjornharvold** [triggerdotdev/jsonhero-web#95]
Getting this consistently when leaving the app open in a browser tab.

Guessing the Service Worker / CDN is to blame for this.

![screencapture-jsonhero-io-2022-09-16-10_07_55](https://user-images.githubusercontent.com/641791/190548585-1b45e20f-88d2-4a41-882e-eb4bb7928e09.png)

**Comment by ericallam** [comment]
Thanks for the report! How long about does it take for this to happen? I'm guessing you are on the JSON viewer page when this occurs?

**Comment by bjornharvold** [comment]
Hi @ericallam 

I just leave the browser open all day. Some time I leave the laptop in suspend and open it again the next day.

I've received this a couple of times now.

**Comment by ericallam** [comment]
I've managed to recreate this issue: it happens when you are viewing JSON and lose internet access, and then we attempt to fetch the details of a URL preview. It could be happening in this file here: https://github.com/apihero-run/jsonhero-web/blob/main/app/components/Preview/Types/PreviewUri.tsx

**Comment by tobihans** [comment]
I'd like to try this. 

/attempt #95
